spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parqueaderodb
    username: admin
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
jwt:
  secret: "MiClaveSuperSecretaEnBase64OTextoPlano"